service: star-wars-api
app: star-wars-api
org: jordysarmiento

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  environment:
    ACCOUNT_ID: 800713300422
    DYNAMODB_TABLE: CharactersTable
    REGION: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource:
          - arn:aws:dynamodb:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/${self:provider.environment.DYNAMODB_TABLE}
        - Effect: Allow
          Action:
          - dynamodb:Query
          - dynamodb:Scan
          Resource:
          - arn:aws:dynamodb:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/${self:provider.environment.DYNAMODB_TABLE}/index/*

plugins:
  - serverless-offline

functions:
  getCharacters:
    handler: src/characters/router.getAll
    events:
      - httpApi:
          method: GET
          path: "/characters"

  createCharacters:
    handler: src/characters/router.create
    events:
      - httpApi:
          method: POST
          path: "/characters"

  getByIdCharacters:
    handler: src/characters/router.getById
    events:
      - httpApi:
          method: GET
          path: "/characters/{id}"

  updateCharacters:
    handler: src/characters/router.update
    events:
      - httpApi:
          method: PUT
          path: "/characters/{id}"

  deleteCharacters:
    handler: src/characters/router.deleteOne
    events:
      - httpApi:
          method: DELETE
          path: "/characters/{id}"

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
